### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [tomerten/financejson#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 1.0.1b8. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary financejson -w /tmp/ext financejson==1.0.1b8
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting financejson==1.0.1b8
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/516/8166f9289d384/financeJSON-1.0.1b8.tar.gz (4.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-ob6oyei_/financejson/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-ob6oyei_/financejson/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-ob6oyei_/financejson/pip-egg-info
         cwd: /tmp/pip-wheel-ob6oyei_/financejson/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-ob6oyei_/financejson/setup.py", line 10, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by tomerten** [comment]
Thanks for reporting the issue, I will try to update the code one of the next days.
